#  simple.yaml  DEFAULT_GROUP       相同配置文件
spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.71.129/ybxt_db?serverTimezone=UTC
    username: root
    password: root

  cloud:
    sentinel:
      transport:
        dashboard: 192.168.71.129:8858

feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        logger-level: BASIC

  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50

logging:
  level:
    feign: debug

seata:
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.71.129:8848
      namespace: 74a950e8-5478-41a2-a3f7-9dddc8b21972
      group: DEFAULT_GROUP
      application: seata-tc-server
      username: nacos
      password: nacos

  tx-service-group: person_data_group
  data-source-proxy-mode: AT

  service:
    vgroup-mapping:
      person_data_group: test

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

jetcache:
  statIntervalMinutes: 1
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 100

  remote:
    default:
      type: redis
      host: 192.168.71.129
      port: 6379
      poolConfig:
        maxTotal: 50    #最大连接数

management:
  endpoint:
    health: #开放健康指标
      show-details: always
    info:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"          #开启全部信息
  info:
    env:
      enabled: true
