spring:
  application:
    name: SYNC-server

server:
  port: 8080

themis:
  address:
    ip: localhost
    port: 50000
    protocol: http://
    prefix: /api/v1

  server:
    name: A
    ip: localhost
    colony: A
    namespace: A
    udo-port: 12345   # 与themis-udp广播通信的端口

  follow-status-timeout: 5000  # 毫秒
  heartbeat-timeout: 500 # 毫秒

  leader:
    heartbeat-timeout: 500   # leader发送心跳间隔  毫秒
    time-out: 60   # leader超时时间  秒
    server-List-time: 1000 # leader同步服务列表间隔  毫秒