spring:
  cloud:
    #路由配置
    gateway:
      default-filters:
        - AddRequestHeader=origin, gateway

      routes:
        - id: identity-server
          uri: lb://identity-server
          predicates:
            - Path=/identity/**

        - id: nucleic-acid-server
          uri: lb://nucleic-acid-server
          predicates:
            - Path=/nucleicacid/**

        - id: trace-server
          uri: lb://trace-server
          predicates:
            - Path=/trace/**

        - id: vaccines-server
          uri: lb://vaccines-server
          predicates:
            - Path=/vaccines/**

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:55550"
              - "http://localhost:55551"
              - "http://localhost:55552"
              - "http://localhost:55553"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000

management:
  endpoint:
    health: #开放健康指标
      show-details: always
    info:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"          #开启全部信息
  info:
    env:
      enabled: true

info: #自定义信息
  author: wzx
  message: gateway
  app-name: Health-code-system-based-on-distributed-and-blockchain
  version: snapshot-1